image: maven:3.8.5-openjdk-17

tasks:
  - name: Build and Run
    command: |
      mvn clean install
      mvn spring-boot:run &
      gp await-port 8080
      gp preview $(gp url 8080) --external

ports:
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-spring-boot
    - vscjava.vscode-java-pack
